name: prek-action
description: Run pre-commit hooks using prek
inputs:
  extra-args:
    description: Options to pass to `prek run`
    required: false
    default: '--all-files'
  extra_args:
    description: Options to pass to `prek run` (deprecated, use extra-args)
    required: false
  install-only:
    description: Only install prek, do not run it
    required: false
    default: 'false'
  prek-version:
    description: Version of prek to install (e.g., '0.2.1', 'latest')
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
  - name: Resolve download URL
    id: resolve
    run: |
      if [ "${{ inputs.prek-version }}" = "latest" ]; then
        echo "version=latest" >> $GITHUB_OUTPUT
        echo "base_url=https://github.com/j178/prek/releases/latest/download/" >> $GITHUB_OUTPUT
      else
        VERSION="${{ inputs.prek-version }}"
        VERSION="${VERSION#v}"
        VERSION="v$VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "base_url=https://github.com/j178/prek/releases/download/$VERSION/" >> $GITHUB_OUTPUT
      fi
    shell: bash
  - name: Install prek
    run: "curl --proto '=https' --tlsv1.2 -LsSf ${{ steps.resolve.outputs.base_url }}prek-installer.sh | sh"
    shell: bash
    if: runner.os != 'Windows'
  - name: Install prek (Windows)
    run: 'powershell -ExecutionPolicy Bypass -c "irm ${{ steps.resolve.outputs.base_url }}prek-installer.ps1 | iex"'
    shell: powershell
    if: runner.os == 'Windows'
  - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: |
        ~/.cache/prek
        ~\AppData\Local\prek
      key: prek-v1|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles('**/.pre-commit-config.yaml') }}
    if: inputs.install-only == 'false'
  - run: prek run --show-diff-on-failure --color=always ${{ inputs.extra_args || inputs.extra-args }}
    shell: bash
    if: inputs.install-only == 'false'
branding:
  icon: 'git-commit'
  color: 'orange'
