name: prek-action
description: Run pre-commit hooks using prek
inputs:
  extra_args:
    description: Options to pass to `prek run`
    required: false
    default: '--all-files'
  prek-version:
    description: Version of prek to install (e.g., '0.2.1', 'latest')
    required: false
    default: 'latest'
runs:
  using: composite
  steps:
  - name: Install prek
    run: |
      if [ "${{ inputs.prek-version }}" = "latest" ]; then
        python -m pip install prek
      else
        python -m pip install prek==${{ inputs.prek-version }}
      fi
    env:
      PIP_DISABLE_PIP_VERSION_CHECK: 1
      PIP_PROGRESS_BAR: 'off'
    shell: bash
  - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: ~/.cache/prek
      key: prek-v1|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles('**/.pre-commit-config.yaml') }}
  - run: prek run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
branding:
  icon: 'git-commit'
  color: 'orange'
